### ISSUE TITLE
ERROR in Error encountered resolving symbol values statically. 

### ISSUE THREAD

**Issue by makhin** [rodolfocop/ng2-mask-money#17]
ERROR in Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NgModule in node_modules/ng2-money-mask/node_modules/@angular/core/core.
d.ts, resolving symbol MoneyMaskModule in node_modules/ng2-money-mask/src/mask/money-mask.module.ts, resolving symbol MoneyMaskModule in node_modules/ng2-money-mask/src/mask/money-mask.module.ts

@angular/cli@1.0.6

**Comment by rodolfocop** [comment]
Hi, you could you tell which version you are using?
I just run test using Angular-cli v1.0 and v4.0 to Angular.

**Comment by rodolfocop** [comment]
Hi, I'm closing this issue. 
Please, this erro keeps, open new questions.
