### ISSUE TITLE
rxjs error

### ISSUE THREAD

**Issue by dhniels** [rodolfocop/ng2-mask-money#22]
get this error when gulp is compiling the typescript. I believe this is issue was caused by an incompatibility between the newer version of typescript and rxjs... i think upgrading rxjs to latest should resolve the issue...?

error TS2415: Class 'Subject<T>' incorrectly extends base class 'Observable<T>'.

**Comment by dhniels** [comment]
found the issue on rxjs repo here https://github.com/ReactiveX/rxjs/issues/2705

**Comment by robbihun** [comment]
```
ERROR in node_modules/ng2-money-mask/node_modules/rxjs/Subject.d.ts(16,22): error TS2415: Class 'Subject<T>' incorrectly extends base class 'Observable<T>'.
  Types of property 'lift' are incompatible.
    Type '<R>(operator: Operator<T, R>) => Observable<T>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<R>'.
      Type 'Observable<T>' is not assignable to type 'Observable<R>'.
        Type 'T' is not assignable to type 'R'.
```

I agree, it seems upgrading to the latest rxjs will fix this.

**Comment by rodolfocop** [comment]
Hi, try to use this new version #28

**Comment by rodolfocop** [comment]
Hi, I'm closing this issue. 

Please, this erro keeps, open new questions.
