### ISSUE TITLE
error TS7006: Parameter 'v' implicitly has an 'any' type

### ISSUE THREAD

**Issue by dhniels** [rodolfocop/ng2-mask-money#23]
get this error on type script compile. should just change it to v:any to solve the error, i think... or maybe its due to your typescript version.... perhaps updating typescript will resolve it...

/node_modules/ng2-money-mask/src/mask/money-mask.directive.ts(49,83): error TS7006: Parameter 'v' implicitly has an 'any' type.

**Comment by rodolfocop** [comment]
Hi we are updating the project to the last version (5.2.1) of the angular and CLI 1.6.5
We will update soon.

**Comment by rodolfocop** [comment]
I'm closing this issue, use version # 35 to fix your issue.
