### ISSUE TITLE
Install ubuntu

### ISSUE THREAD

**Issue by john182** [rodolfocop/ng2-mask-money#25]
notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

**Comment by rodolfocop** [comment]
Hi, this problem is linked to npm. 
Try to see if that solves for you.
[NPM](https://github.com/npm/npm/issues/9204) or [ANGULAR](https://github.com/angular/angular-cli/issues/8881)
