### ISSUE TITLE
I'm having trouble using this with Visual Studio Code

### ISSUE THREAD

**Issue by mprmax** [rodolfocop/ng2-mask-money#26]
When I install this using npm install ng2-mask-money everything is installed correctly. I then add the appropriate bits to the AppModule. However whenever I run the app I keep getting a 404 error

http://localhost:8808/node_modules/ng2-money-mask/ 404 (Not Found)

I'm a very novice Angular 2 programmer but I can't for the life of me figure out what I'm doing wrong. Any help much appreciated

**Comment by rodolfocop** [comment]
Hi, sorry for the delay, could you tell me the version of your Angular project?

**Comment by rodolfocop** [comment]
Hi, try to use this new version #28

**Comment by rodolfocop** [comment]
Hi, I am closing these issues if the problem still persists again
