### ISSUE TITLE
is there any option to restrict number of integer places

### ISSUE THREAD

**Issue by kshitij-kasliwal-bkst** [rodolfocop/ng2-mask-money#29]
I can see option to restrict number of decimal places. Is there any option to restrict no of integer places. I want to restrict money field to 17,2 format.

**Comment by rodolfocop** [comment]
Hi, we did not put this option to restrict the integer values.
We can make this change, but not this today.
If you want to help us, send us PR.

**Comment by rodolfocop** [comment]
Hi, this problem is solved #31
