### ISSUE TITLE
 TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.

### ISSUE THREAD

**Issue by lucasbadv8** [rodolfocop/ng2-mask-money#34]
Ao tentar usar o pacote, o build apresentou o seguinte erro:

ERROR in node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/ng2-money-mask/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.

Existem duas variáveis globais com o mesmo nome.
poderia exportar apenas o .js?

**Comment by rodolfocop** [comment]
Opa, qual a versão do angular que está utilizando? Esse erro acontece quando você esta utilizando versão diferente da que o meu projeto utiliza. 
Me envie quais são para que eu possa atualizar para sua versão para que esse erro desapareça.

**Comment by rodolfocop** [comment]
@andrepesi não atualizei o mesmo para a versão 6. Acredito que até semana que vem faço isso. Caso queira contribuir fique a vontade em ajudar. abrs

**Comment by BlahaMarek** [comment]
Hello, is it already updated for Angular 6 ? Thanks

**Comment by dann95** [comment]
@rodolfocop alguma novidade sobre atualização para versão 6?

**Comment by rodolfocop** [comment]
@dann95 estarei atualizando esta semana e lhe informo!

**Comment by rodolfocop** [comment]
@dann95 esta atualizado você pode baixa-lo hoje mesmo!

@BlahaMarek Hi, I've made an update.

#35

**Comment by dann95** [comment]
@rodolfocop obg, vou olhar os commits pra entender.
