### ISSUE TITLE
Can't autoselect all text on focus

### ISSUE THREAD

**Issue by cdarrigo** [rodolfocop/ng2-mask-money#5]
When the control receives focus, I'd like the entire control value to be auto-selected so the user can easily overwrite the existing value. 

Calling .select() on the item's onFocus() method gets overwritten by the directive's control of the element.

**Comment by rodolfocop** [comment]
Hi @cdarrigo, I'm going to add this option in the directive. 
In a few days I'll be making this available.

**Comment by phsilva** [comment]
Hey @rodolfocop, any progress on this issue? Otherwise will try to send a PR for it.

**Comment by rodolfocop** [comment]
Hi @phsilva, I have not had time to solve this problem yet. 
If you can help me just send me a PR with this bug fixed.
Thanks.

**Comment by rodolfocop** [comment]
Hi, I'm closing this issue. 
Please, this erro keeps, open new questions.
